# Generated by Django 3.0.5 on 2020-04-14 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
