# Generated by Django 3.0.5 on 2020-04-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200420_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcar',
            name='title',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
