# Generated by Django 3.0.5 on 2020-04-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200420_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcar',
            name='gear',
            field=models.CharField(choices=[('automat', 'Automat'), ('manual', 'Manual')], default='manual', max_length=32),
        ),
        migrations.AddField(
            model_name='newcar',
            name='model',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='newcar',
            name='petrol',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('benzin', 'Benzin'), ('gas', 'Gas')], default='diesel', max_length=32),
        ),
        migrations.AddField(
            model_name='newcar',
            name='price',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='newcar',
            name='year',
            field=models.CharField(max_length=32),
        ),
    ]
