# Generated by Django 3.0.5 on 2020-04-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200422_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcar',
            name='model',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
