# Generated by Django 3.0.5 on 2020-04-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_newcar_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcar',
            name='year',
            field=models.CharField(max_length=32),
        ),
    ]
