# Generated by Django 3.0.5 on 2020-04-22 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20200422_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcar',
            name='year',
        ),
    ]
