# Generated by Django 3.0.5 on 2020-04-22 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200422_2347'),
        ('app', '0025_newcar_year'),
    ]

    operations = [
    ]
