# Generated by Django 3.0.5 on 2020-04-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_merge_20200422_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcar',
            name='year',
            field=models.DateField(null=True),
        ),
    ]
