# Generated by Django 3.0.5 on 2020-04-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20200422_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcar',
            name='gear',
            field=models.CharField(choices=[('automat', 'Automat'), ('manual', 'Manual')], max_length=32),
        ),
        migrations.AlterField(
            model_name='newcar',
            name='petrol',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('benzin', 'Benzin'), ('gas', 'Gas')], max_length=32),
        ),
        migrations.AlterField(
            model_name='newcar',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='newcar',
            name='year',
            field=models.DateField(),
        ),
    ]
