# Generated by Django 3.0.5 on 2020-04-22 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20200423_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcar',
            name='year',
        ),
    ]
