# Generated by Django 3.0.5 on 2020-04-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_newcar_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcar',
            name='year',
            field=models.CharField(default=2010, max_length=32),
        ),
    ]
