# Generated by Django 3.0.5 on 2020-04-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20200423_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcar',
            name='year',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
