# Generated by Django 3.0.5 on 2020-04-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20200423_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcar',
            name='image',
            field=models.ImageField(default=None, upload_to='profile_pics'),
        ),
    ]
