# Generated by Django 3.0.5 on 2020-04-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20200423_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcar',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
