# Generated by Django 3.0.5 on 2020-04-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20200423_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcar',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/'),
        ),
    ]
