# Generated by Django 3.0.5 on 2020-04-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='title',
            field=models.CharField(default='Search', max_length=100),
        ),
    ]
