# Generated by Django 3.0.5 on 2020-05-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20200506_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcar',
            name='link',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
